### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by nu-vi** [dannvix/keylogger-osx#2]
What do mean by build the code? what exactly should I move to /usr/local/sbin/? 
Sorry I'm new to programming but I would very much like to use this script instead of a keylogger software.

Thanks!

**Comment by dannvix** [comment]
Hi @nunada. Firstly you should have XCode and its command-line tools installed. Secondly use "make" (in the project folder) to produce an executable binary named "keylogger," which should be copied into /usr/local/sbin then.

Speaking frankly, if you are not familiar with such build-and-configure things, I would suggest you to try other commercial keylogger package that can be easily installed.

Thanks.

**Comment by nu-vi** [comment]
Got it, apparently i had to download missing contents from XCode since i've recently installed the update

Thanks.

**Comment by yarodevuci** [comment]
Where is Launchd script?
